### ISSUE TITLE
destructive_warning stuck on True / not working as expected

### ISSUE THREAD

**Issue by saxomagic** [databricks/databricks-sql-cli#40]

**Comment by saxomagic** [comment]
The config setting for enabling/disabling the warning about destructive commands and prompting for yes/no (`destructive_warning = True | False`), seems to be stuck on `True`, always warning and prompting.

The config file is at `~/.dbsqlcli/dbsqlclirc` by default, but can also be specified explicitly via the `--clirc FILE` command line switch.

Have confirmed that other settings, such as key bindings set to vi do take effect, so the file is sourced, yet even with:

```
destructive_warning = False
``

you are still prompted if you do something like:

```sql
delete from table_name;
```

**Comment by xialinlin101** [comment]
The configuration "destructive_warning " is read as a string, but is judged later as a boolean. If you want to make the configuration work, Configure "destructive_warning =" or Modify ${PYTHON_HOME}/site-packages/dbsqlcli/main.py 113 behavior `self.destructive_warning = _cfg["main"].as_bool("destructive_warning")`

**Comment by entong** [comment]
Can confirm this is not working as expected. cc @susodapop

**Comment by susodapop** [comment]
Thanks for calling this out and for the fix @xialinlin101! We're cutting a release with this fix shortly.
